# coding: utf-8
# Si vous avez d'autre cartes que vous voulez mettre, il suffit de
# les mettre dans la liste le programme va automatiquement chercher
# deux fichier: nom+'R.jpg' et nom+'B.jpg', il vous faudra donc deux
# images avec deux fonds différents. Ensuite il faut rajouter ses
# caractéristiques, dans le sens des aiguilles d'une montre, et en
# dernier son élément. (Feu, eau, air, terre, foudre, sacré, poison, glace.)
allCards = [
    "Gimp",
    "Audacity",
    "Firefox",
    "Xonotic",
    "Libre Office",
    "Vlc",
    "Blender",
    "Armagetronadvanced",
    "Gltron",
    "Inkscape",
    "Mumble",
    "Musescore",
    "Notepad++",
    "Scribus",
    "Pygame",
    "Thunderbird",
    "Python",
    "Xchat",
    "OmegaT",
    "Linphone",
    "Ruby",
    "Github",
    "Calibre",
    "GNU",
    "Sunflower",
    "Ray",
    "Asf",
    "Debian",
    "Gnome",
    "KDE",
    "Mysql",
    "Octopi",
    "Open BSD",
    "Php",
    "Ubuntu",
    "MediaWiki",
    "Postfix",
    "Tux",
    "Ppsspp",
    "Clementine",
    "Wine",
    "Dosbox",
    "Freemind",
    "Latex",
    "Pidgin",
    "Visualboyadvance",
    "Docker",
    "fileZilla",
    "Gecko",
    "Gens",
    "goeGebra",
    "html5",
    "Jenkins",
    "rolisteam",
    "Drupal",
    "Unvanquished"
    ]
values = [
    ['A', '4', '6', '9', None, None],
    ['6', '9', 'A', '4', None, None],
    ['4', 'A', '2', 'A', None, None],
    ['A', 'A', '3', '3', None, None],
    ['8', '5', 'A', '6', None, None],
    ['2', '6', '9', 'A', None, None],
    ['A', '8', '2', '6', None, None],
    ['5', '1', '9', '9', "earth", None],
    ['9', '5', '2', '9', "earth", None],
    ['A', '7', '2', '8', None, None],
    ['6', '7', '6', 'A', None, None],
    ['9', '6', 'A', '2', None, None],
    ['A', '8', '6', '4', None, None],
    ['5', 'A', '3', '9', None, None],
    ['7', '4', '6', 'A', None, None],
    ['7', '2', '7', 'A', "fire", None],
    ['9', 'A', '4', '2', "holy", None],
    ['8', 'A', '3', '5', None, None],
    ['8', 'A', '3', '5', None, None],
    ['5', 'A', '8', '3', None, None],
    ['A', '1', '7', '7', "wind", None],
    ['7', 'A', '1', '7', "water", None],
    ['8', '4', 'A', '4', None, None],
    ['8', '9', '6', '2', None, None],
    ['9', '6', '2', '8', "fire", None],
    ['5', '7', '8', '5', None, None],
    ['4', '4', '8', '9', None, None],
    ['2', '9', '9', '4', "thunder", None],
    ['6', '7', '4', '9', "ice", None],
    ['9', '6', '7', '3', None, None],
    ['7', '7', '2', '8', None, None],
    ['9', '3', '9', '2', None, None],
    ['3', '7', '9', '6', None, None],
    ['1', '8', '7', '7', None, None],
    ['9', '4', '8', '4', None, None],
    ['6', '8', '4', '7', None, None],
    ['8', '8', '5', '4', None, None],
    ['8', '3', '5', '8', None, None],
    ['8', '6', '7', '3', None, None],
    ['3', '1', 'A', 'A', "poison", None],
    ['8', '5', '2', '8', "thunder", None],
    ['8', '8', '4', '4', None, None],
    ['8', '4', '4', '8', None, None],
    ['7', '5', '8', '1', None, None],
    ['1', '8', '4', '8', None, None],
    ['6', '5', '4', '8', None, None],
    ['4', '8', '5', '6', None, None],
    ['7', '2', '8', '5', None, None],
    ['2', '8', '8', '4', None, None],
    ['7', '8', '3', '4', None, None],
    ['4', '8', '7', '3', None, None],
    ['8', '2', '8', '2', None, None],
    ['6', '8', '4', '5', None, None],
    ['1', '8', '8', '3', "Poison", None],
    ['4', '6', '7', '6', None, None],
    ['6', '6', '2', '7', None, None]
    ]
